ipAddr: 49.232.68.245
spring:
  application:
    name: meituan-authserver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8333

  session:
    store-type: redis
  redis:
    host: ${ipAddr}
server:
  port: 12000
  # session存活时间
  servlet:
    session:
      timeout: 30m

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000